[audio]
buffer_size = 2048
device = 'default'
sample_rate = 44100

[general]
debug = true

[keyboard]
next_preset = 'Right'
next_track = 'N'
play_pause = 'Space'
prev_preset = 'Left'
prev_track = 'P'
toggle_fullscreen = 'F'
toggle_record = 'R'

[overlay]
enabled = true

    [[overlay.elements]]
    anchor = 'left'
    animation = 'none'
    animation_speed = 1.0
    color = '#FFFFFFFF'
    font_size = 24
    id = 'watermark'
    opacity = 0.69999998807907104
    text = 'ChadVis Player'
    visible = true

        [overlay.elements.position]
        x = 0.019999999552965164
        y = 0.94999998807907104

    [[overlay.elements]]
    anchor = 'center'
    animation = 'fade_pulse'
    animation_speed = 1.0
    color = '#00FF88FF'
    font_size = 36
    id = 'now_playing'
    opacity = 0.89999997615814209
    text = '{artist} - {title}'
    visible = true

        [overlay.elements.position]
        x = 0.5
        y = 0.05000000074505806

[recording]
container = 'mp4'
default_filename = 'chadvis-projectm-qt_{date}_{time}'
enabled = true
output_directory = '/home/nsomnia/Videos/ChadVis'

    [recording.audio]
    bitrate = 320
    codec = 'aac'

    [recording.video]
    codec = 'libx264'
    crf = 18
    fps = 60
    height = 1080
    pixel_format = 'yuv420p'
    preset = 'medium'
    width = 1920

[ui]
accent_color = '#00FF88FF'
show_debug_panel = false
show_playlist = true
show_presets = true
theme = 'dark'
visualizer_background = '#000000FF'

[visualizer]
beat_sensitivity = 1.0
force_preset = ''
fps = 60
height = 1080
preset_duration = 30
preset_path = '/usr/share/projectM/presets'
shuffle_presets = true
smooth_preset_duration = 5
use_default_preset = false
width = 1920